[package]
name = "metamind"
version = "0.0.0"
description = "AI-Powered File Intelligence System"
authors = ["MetaMind Team"]
license = "MIT"
repository = "https://github.com/metamind/metamind"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5.0", features = [] }

[dependencies]
tauri = { version = "1.5.0", features = ["api-all", "shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "sqlite", "chrono", "uuid"] }
qdrant-client = "1.7"
notify = "6.1"
walkdir = "2.4"
uuid = { version = "1.6", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
anyhow = "1.0"
thiserror = "1.0"
image = "0.24"
pdf-extract = "0.7"
docx-rs = "0.4"
mp3-metadata = "0.3"
exif = "0.5"
tantivy = "0.21"
rayon = "1.8"
once_cell = "1.19"
parking_lot = "0.12"
tracing = "0.1"
tracing-subscriber = "0.3"
dirs = "5.0"
num_cpus = "1.16"
sysinfo = "0.29"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]